#!/usr/bin/env sh

mv Figure_001-a.pdf diag_T1tttt.pdf 
mv Figure_001-b.pdf diag_T5ttbbWW.pdf 
mv Figure_001-c.pdf diag_T5tttt.pdf 
mv Figure_001-d.pdf diag_T5ttcc.pdf 
mv Figure_001-e.pdf diag_T5qqqqWZ.pdf 
mv Figure_002-a.pdf diag_T6ttWW.pdf 
mv Figure_002-b.pdf diag_T6ttHZ.pdf 
mv Figure_003-a.pdf diag_T1qqqqL.pdf 
mv Figure_003-b.pdf diag_T1tbs.pdf 
mv Figure_004-a.pdf br_ht.pdf 
mv Figure_004-b.pdf br_met.pdf 
mv Figure_004-c.pdf br_mtmin.pdf 
mv Figure_004-d.pdf br_njets.pdf 
mv Figure_004-e.pdf br_nbtags.pdf 
mv Figure_004-f.pdf br_charge.pdf 
mv Figure_005-a.pdf SRHH_TOTAL.pdf 
mv Figure_005-b.pdf SRHL_TOTAL.pdf 
mv Figure_005-c.pdf SRLL_TOTAL.pdf 
mv Figure_006-a.pdf SRLM_TOTAL.pdf 
mv Figure_006-b.pdf SRMLONZ_TOTAL.pdf 
mv Figure_006-c.pdf SRMLOFFZ_TOTAL.pdf 
mv Figure_007-a.pdf scan_t1tttt.pdf 
mv Figure_007-b.pdf scan_t1ttbb.pdf 
mv Figure_007-c.pdf scan_t5tttt.pdf 
mv Figure_007-d.pdf scan_t5ttcc.pdf 
mv Figure_008-a.pdf scan_t5qqqqvv.pdf 
mv Figure_008-b.pdf scan_t5qqqqvvdm20.pdf 
mv Figure_009-a.pdf scan_t5qqqqww.pdf 
mv Figure_009-b.pdf scan_t5qqqqwwdm20.pdf 
mv Figure_010-a.pdf scan_t6ttww.pdf 
mv Figure_011-a.pdf scan_t6tthzbrh.pdf 
mv Figure_011-b.pdf scan_t6tthzbrb.pdf 
mv Figure_011-c.pdf scan_t6tthzbrz.pdf 
mv Figure_012-a.pdf scan_rpv_t1qqqql.pdf 
mv Figure_012-b.pdf scan_rpv_t1tbs.pdf 
mv Figure_013-a.pdf scan_milimits_met.pdf 
mv Figure_013-b.pdf scan_milimits_ht.pdf 
